server.port=8080
spring.config.import=optional:file:.env[.properties]
app.datasource.driver-class=com.mysql.cj.jdbc.Driver
app.datasource.jdbc-url=${DB_URL:jdbc:mysql://localhost:3306/service-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Barnaul}
app.datasource.user=${DB_USERNAME:root}
app.datasource.password=${DB_PASSWORD:123456a@}
app.datasource.min-pool-size=3
app.datasource.max-pool-size=10
app.datasource.checkout-timeout=50000
app.datasource.max-statements=150
app.datasource.idle-connection-test-period=30
app.datasource.max-idle-time=1800
app.datasource.test-connection-on-checkout=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.fetch_size=200
app.scheduler.pool-size=5
